.PHONY: clean All

All:
	@echo "----------Building project:[ XpressController-codelite - Debug ]----------"
	@"$(MAKE)" -f  "XpressController-codelite.mk"
clean:
	@echo "----------Cleaning project:[ XpressController-codelite - Debug ]----------"
	@"$(MAKE)" -f  "XpressController-codelite.mk" clean
