package hu.bme.mit.inf.piclient.ui;

import java.awt.BorderLayout;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import org.apache.batik.swing.JSVGCanvas;
import hu.bme.mit.inf.piclient.Application;

/**
 *
 * @author zsoltmazlo
 */
public class RailwayWindow extends javax.swing.JFrame {

    private final JSVGCanvas canvas = new JSVGCanvas();
    private final String svgFileName = "/hu/bme/mit/inf/piclient/ui/layout.svg";

    /**
     * Creates new form Application
     */
    public RailwayWindow() {
        initComponents();
        
        getContentPane().setBackground(Application.pageBackground);

        this.canvasHolder.setLayout(new BorderLayout());
        this.canvasHolder.add("Center", canvas);
        File svgFile = new File(svgFileName);
        canvas.addSVGLoadEventDispatcherListener(new SVGLoadAdapter(canvas, this));
        canvas.setPreferredSize(this.canvasHolder.getSize());
        canvas.setSize(this.canvasHolder.getSize());
        canvas.setURI(RailwayWindow.class.getResource(svgFileName).toString());
        canvas.setDocumentState(JSVGCanvas.ALWAYS_DYNAMIC);

        RailwayWindow.consoleHolder.setLayout(new BoxLayout(RailwayWindow.consoleHolder, BoxLayout.Y_AXIS));
        RailwayWindow.log("GUI setted up");
    }

    public void startTurnoutRefresherThread() {
        Thread thread = new Thread(new SVGRefresher(canvas));
        thread.start();
    }

    public final static void log(String message) {
        Calendar calendar = Calendar.getInstance();
        Date now = calendar.getTime();

        String content = String.format("%02d:%02d-%s", now.getHours(), now.getMinutes(), message);

        JLabel entry = new JLabel("<html><body style='width: 192px; margin: 0 3px'>" + content + "</body></html>");
        entry.setFont(Application.labelFont);
        entry.setForeground(Application.labelForeground);
        RailwayWindow.consoleHolder.add(entry);
        RailwayWindow.consoleHolder.revalidate();

        JScrollBar vertical = RailwayWindow.jScrollPane1.getVerticalScrollBar();
        vertical.setValue(vertical.getMaximum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consoleHolder = new javax.swing.JPanel();
        imagePanel1 = new hu.bme.mit.inf.piclient.ui.ImagePanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        canvasHolder = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        viewMenu = new javax.swing.JMenu();
        showConsole = new javax.swing.JCheckBoxMenuItem();
        settingsMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Application.pageBackground);
        setMinimumSize(new java.awt.Dimension(567, 370));

        jPanel1.setBackground(Application.pageBackground);
        jPanel1.setMinimumSize(new java.awt.Dimension(662, 323));

        jScrollPane1.setBackground(Application.pageBackground);
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, Application.titleFont, Application.titleForeground));
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(192, 323));

        consoleHolder.setBackground(Application.pageBackground);
        consoleHolder.setForeground(Application.labelForeground);
        consoleHolder.setFont(Application.labelFont);

        javax.swing.GroupLayout consoleHolderLayout = new javax.swing.GroupLayout(consoleHolder);
        consoleHolder.setLayout(consoleHolderLayout);
        consoleHolderLayout.setHorizontalGroup(
            consoleHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        consoleHolderLayout.setVerticalGroup(
            consoleHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(consoleHolder);

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jLayeredPane1.setBackground(new java.awt.Color(153, 153, 0));

        canvasHolder.setBackground(new java.awt.Color(255, 255, 255));
        canvasHolder.setMinimumSize(new java.awt.Dimension(464, 323));
        canvasHolder.setPreferredSize(new java.awt.Dimension(464, 323));

        javax.swing.GroupLayout canvasHolderLayout = new javax.swing.GroupLayout(canvasHolder);
        canvasHolder.setLayout(canvasHolderLayout);
        canvasHolderLayout.setHorizontalGroup(
            canvasHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        canvasHolderLayout.setVerticalGroup(
            canvasHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(canvasHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(canvasHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jLayeredPane1.setLayer(canvasHolder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        jMenuBar1.setBackground(Application.pageBackground);
        jMenuBar1.setForeground(Application.titleForeground);
        jMenuBar1.setFont(Application.titleFont);

        viewMenu.setBackground(Application.pageBackground);
        viewMenu.setForeground(Application.titleForeground);
        viewMenu.setText("View");
        viewMenu.setActionCommand("view");
        viewMenu.setFont(Application.titleFont);

        showConsole.setBackground(Application.pageBackground);
        showConsole.setFont(Application.titleFont);
        showConsole.setForeground(Application.titleForeground);
        showConsole.setSelected(true);
        showConsole.setText("Show console");
        showConsole.setActionCommand("showConsole");
        showConsole.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showConsoleStateChanged(evt);
            }
        });
        viewMenu.add(showConsole);

        jMenuBar1.add(viewMenu);

        settingsMenu.setBackground(Application.pageBackground);
        settingsMenu.setForeground(Application.titleForeground);
        settingsMenu.setText("Settings");
        settingsMenu.setFont(Application.titleFont);
        settingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(settingsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showConsoleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showConsoleStateChanged

        if (showConsole.getState()) {
            jScrollPane1.setVisible(true);
        } else {
            jScrollPane1.setVisible(false);
        }

    }//GEN-LAST:event_showConsoleStateChanged

    private void settingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMenuMouseClicked
        SettingsWindow settings = new SettingsWindow();
        settings.setVisible(true);
    }//GEN-LAST:event_settingsMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvasHolder;
    private static javax.swing.JPanel consoleHolder;
    private hu.bme.mit.inf.piclient.ui.ImagePanel imagePanel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JCheckBoxMenuItem showConsole;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
