/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.inf


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ParametricTimedRegularExpressionRuntimeModule extends AbstractParametricTimedRegularExpressionRuntimeModule {
}
