/*
 * generated by Xtext
 */
package hu.bme.mit.ftsrg.ptregex;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RegularExpressionRuntimeModule extends hu.bme.mit.ftsrg.ptregex.AbstractRegularExpressionRuntimeModule {

}
