// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DccOperationsCommand.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DccOperationsCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace modes3 {
namespace protobuf {
class DccOperationsCommandDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DccOperationsCommand>
     _instance;
} _DccOperationsCommand_default_instance_;

namespace protobuf_DccOperationsCommand_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DccOperationsCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DccOperationsCommand, dccoperations_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(DccOperationsCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_DccOperationsCommand_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "DccOperationsCommand.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::modes3::protobuf::protobuf_Enums_2eproto::InitDefaults();
  _DccOperationsCommand_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DccOperationsCommand_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032DccOperationsCommand.proto\022\017modes3.pro"
      "tobuf\032\013Enums.proto\"M\n\024DccOperationsComma"
      "nd\0225\n\rdccOperations\030\001 \001(\0162\036.modes3.proto"
      "buf.DccOperationsB0\n,hu.bme.mit.inf.mode"
      "s3.messaging.mms.messagesP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 195);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DccOperationsCommand.proto", &protobuf_RegisterTypes);
  ::modes3::protobuf::protobuf_Enums_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_DccOperationsCommand_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DccOperationsCommand::kDccOperationsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DccOperationsCommand::DccOperationsCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_DccOperationsCommand_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:modes3.protobuf.DccOperationsCommand)
}
DccOperationsCommand::DccOperationsCommand(const DccOperationsCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  dccoperations_ = from.dccoperations_;
  // @@protoc_insertion_point(copy_constructor:modes3.protobuf.DccOperationsCommand)
}

void DccOperationsCommand::SharedCtor() {
  dccoperations_ = 0;
  _cached_size_ = 0;
}

DccOperationsCommand::~DccOperationsCommand() {
  // @@protoc_insertion_point(destructor:modes3.protobuf.DccOperationsCommand)
  SharedDtor();
}

void DccOperationsCommand::SharedDtor() {
}

void DccOperationsCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DccOperationsCommand::descriptor() {
  protobuf_DccOperationsCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DccOperationsCommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DccOperationsCommand& DccOperationsCommand::default_instance() {
  protobuf_DccOperationsCommand_2eproto::InitDefaults();
  return *internal_default_instance();
}

DccOperationsCommand* DccOperationsCommand::New(::google::protobuf::Arena* arena) const {
  DccOperationsCommand* n = new DccOperationsCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DccOperationsCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:modes3.protobuf.DccOperationsCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dccoperations_ = 0;
  _internal_metadata_.Clear();
}

bool DccOperationsCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:modes3.protobuf.DccOperationsCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .modes3.protobuf.DccOperations dccOperations = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_dccoperations(static_cast< ::modes3::protobuf::DccOperations >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:modes3.protobuf.DccOperationsCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:modes3.protobuf.DccOperationsCommand)
  return false;
#undef DO_
}

void DccOperationsCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:modes3.protobuf.DccOperationsCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .modes3.protobuf.DccOperations dccOperations = 1;
  if (this->dccoperations() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->dccoperations(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:modes3.protobuf.DccOperationsCommand)
}

::google::protobuf::uint8* DccOperationsCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:modes3.protobuf.DccOperationsCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .modes3.protobuf.DccOperations dccOperations = 1;
  if (this->dccoperations() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->dccoperations(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modes3.protobuf.DccOperationsCommand)
  return target;
}

size_t DccOperationsCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modes3.protobuf.DccOperationsCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .modes3.protobuf.DccOperations dccOperations = 1;
  if (this->dccoperations() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->dccoperations());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DccOperationsCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:modes3.protobuf.DccOperationsCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const DccOperationsCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DccOperationsCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:modes3.protobuf.DccOperationsCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:modes3.protobuf.DccOperationsCommand)
    MergeFrom(*source);
  }
}

void DccOperationsCommand::MergeFrom(const DccOperationsCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:modes3.protobuf.DccOperationsCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.dccoperations() != 0) {
    set_dccoperations(from.dccoperations());
  }
}

void DccOperationsCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:modes3.protobuf.DccOperationsCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DccOperationsCommand::CopyFrom(const DccOperationsCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modes3.protobuf.DccOperationsCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DccOperationsCommand::IsInitialized() const {
  return true;
}

void DccOperationsCommand::Swap(DccOperationsCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DccOperationsCommand::InternalSwap(DccOperationsCommand* other) {
  using std::swap;
  swap(dccoperations_, other->dccoperations_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DccOperationsCommand::GetMetadata() const {
  protobuf_DccOperationsCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DccOperationsCommand_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DccOperationsCommand

// .modes3.protobuf.DccOperations dccOperations = 1;
void DccOperationsCommand::clear_dccoperations() {
  dccoperations_ = 0;
}
::modes3::protobuf::DccOperations DccOperationsCommand::dccoperations() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.DccOperationsCommand.dccOperations)
  return static_cast< ::modes3::protobuf::DccOperations >(dccoperations_);
}
void DccOperationsCommand::set_dccoperations(::modes3::protobuf::DccOperations value) {
  
  dccoperations_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.DccOperationsCommand.dccOperations)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace modes3

// @@protoc_insertion_point(global_scope)
