// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace modes3 {
namespace protobuf {
class MessageDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Message>
     _instance;
} _Message_default_instance_;

namespace protobuf_Message_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, segmentcommand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, segmentstate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, trainreferencespeed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, trainreferencespeedcommand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, turnoutcommand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, turnoutstate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, segmentoccupancy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, turnoutreferencestate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, dccoperationscommand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, dccoperationsstate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, allstatus_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, computervisionobjectpositions_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(Message)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Message_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::modes3::protobuf::protobuf_DccOperationsCommand_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_DccOperationsState_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_Enums_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_SegmentCommand_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_SegmentState_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_TrainReferenceSpeed_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_TrainReferenceSpeedCommand_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_TurnoutCommand_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_TurnoutState_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_TurnoutReferenceState_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_SegmentOccupancy_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_SendAllStatus_2eproto::InitDefaults();
  ::modes3::protobuf::protobuf_ComputerVisionObjectPositions_2eproto::InitDefaults();
  _Message_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_Message_default_instance_);_Message_default_instance_._instance.get_mutable()->segmentcommand_ = const_cast< ::modes3::protobuf::SegmentCommand*>(
      ::modes3::protobuf::SegmentCommand::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->segmentstate_ = const_cast< ::modes3::protobuf::SegmentState*>(
      ::modes3::protobuf::SegmentState::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->trainreferencespeed_ = const_cast< ::modes3::protobuf::TrainReferenceSpeed*>(
      ::modes3::protobuf::TrainReferenceSpeed::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->trainreferencespeedcommand_ = const_cast< ::modes3::protobuf::TrainReferenceSpeedCommand*>(
      ::modes3::protobuf::TrainReferenceSpeedCommand::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->turnoutcommand_ = const_cast< ::modes3::protobuf::TurnoutCommand*>(
      ::modes3::protobuf::TurnoutCommand::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->turnoutstate_ = const_cast< ::modes3::protobuf::TurnoutState*>(
      ::modes3::protobuf::TurnoutState::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->segmentoccupancy_ = const_cast< ::modes3::protobuf::SegmentOccupancy*>(
      ::modes3::protobuf::SegmentOccupancy::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->turnoutreferencestate_ = const_cast< ::modes3::protobuf::TurnoutReferenceState*>(
      ::modes3::protobuf::TurnoutReferenceState::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->dccoperationscommand_ = const_cast< ::modes3::protobuf::DccOperationsCommand*>(
      ::modes3::protobuf::DccOperationsCommand::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->dccoperationsstate_ = const_cast< ::modes3::protobuf::DccOperationsState*>(
      ::modes3::protobuf::DccOperationsState::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->allstatus_ = const_cast< ::modes3::protobuf::SendAllStatus*>(
      ::modes3::protobuf::SendAllStatus::internal_default_instance());
  _Message_default_instance_._instance.get_mutable()->computervisionobjectpositions_ = const_cast< ::modes3::protobuf::ComputerVisionObjectPositions*>(
      ::modes3::protobuf::ComputerVisionObjectPositions::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rMessage.proto\022\017modes3.protobuf\032\032DccOpe"
      "rationsCommand.proto\032\030DccOperationsState"
      ".proto\032\013Enums.proto\032\024SegmentCommand.prot"
      "o\032\022SegmentState.proto\032\031TrainReferenceSpe"
      "ed.proto\032 TrainReferenceSpeedCommand.pro"
      "to\032\024TurnoutCommand.proto\032\022TurnoutState.p"
      "roto\032\033TurnoutReferenceState.proto\032\026Segme"
      "ntOccupancy.proto\032\023SendAllStatus.proto\032#"
      "ComputerVisionObjectPositions.proto\"\271\006\n\007"
      "Message\022*\n\004type\030\001 \001(\0162\034.modes3.protobuf."
      "MessageType\0227\n\016segmentCommand\030\002 \001(\0132\037.mo"
      "des3.protobuf.SegmentCommand\0223\n\014segmentS"
      "tate\030\003 \001(\0132\035.modes3.protobuf.SegmentStat"
      "e\022A\n\023trainReferenceSpeed\030\004 \001(\0132$.modes3."
      "protobuf.TrainReferenceSpeed\022O\n\032trainRef"
      "erenceSpeedCommand\030\005 \001(\0132+.modes3.protob"
      "uf.TrainReferenceSpeedCommand\0227\n\016turnout"
      "Command\030\006 \001(\0132\037.modes3.protobuf.TurnoutC"
      "ommand\0223\n\014turnoutState\030\007 \001(\0132\035.modes3.pr"
      "otobuf.TurnoutState\022;\n\020segmentOccupancy\030"
      "\010 \001(\0132!.modes3.protobuf.SegmentOccupancy"
      "\022E\n\025turnoutReferenceState\030\t \001(\0132&.modes3"
      ".protobuf.TurnoutReferenceState\022C\n\024dccOp"
      "erationsCommand\030\n \001(\0132%.modes3.protobuf."
      "DccOperationsCommand\022\?\n\022dccOperationsSta"
      "te\030\013 \001(\0132#.modes3.protobuf.DccOperations"
      "State\0221\n\tallStatus\030\014 \001(\0132\036.modes3.protob"
      "uf.SendAllStatus\022U\n\035computerVisionObject"
      "Positions\030\r \001(\0132..modes3.protobuf.Comput"
      "erVisionObjectPositionsB2\n.hu.bme.mit.in"
      "f.modes3.messaging.proto.messagesP\001b\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1243);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Message.proto", &protobuf_RegisterTypes);
  ::modes3::protobuf::protobuf_DccOperationsCommand_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_DccOperationsState_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_Enums_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_SegmentCommand_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_SegmentState_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_TrainReferenceSpeed_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_TrainReferenceSpeedCommand_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_TurnoutCommand_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_TurnoutState_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_TurnoutReferenceState_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_SegmentOccupancy_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_SendAllStatus_2eproto::AddDescriptors();
  ::modes3::protobuf::protobuf_ComputerVisionObjectPositions_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Message_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Message::kTypeFieldNumber;
const int Message::kSegmentCommandFieldNumber;
const int Message::kSegmentStateFieldNumber;
const int Message::kTrainReferenceSpeedFieldNumber;
const int Message::kTrainReferenceSpeedCommandFieldNumber;
const int Message::kTurnoutCommandFieldNumber;
const int Message::kTurnoutStateFieldNumber;
const int Message::kSegmentOccupancyFieldNumber;
const int Message::kTurnoutReferenceStateFieldNumber;
const int Message::kDccOperationsCommandFieldNumber;
const int Message::kDccOperationsStateFieldNumber;
const int Message::kAllStatusFieldNumber;
const int Message::kComputerVisionObjectPositionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Message::Message()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:modes3.protobuf.Message)
}
Message::Message(const Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_segmentcommand()) {
    segmentcommand_ = new ::modes3::protobuf::SegmentCommand(*from.segmentcommand_);
  } else {
    segmentcommand_ = NULL;
  }
  if (from.has_segmentstate()) {
    segmentstate_ = new ::modes3::protobuf::SegmentState(*from.segmentstate_);
  } else {
    segmentstate_ = NULL;
  }
  if (from.has_trainreferencespeed()) {
    trainreferencespeed_ = new ::modes3::protobuf::TrainReferenceSpeed(*from.trainreferencespeed_);
  } else {
    trainreferencespeed_ = NULL;
  }
  if (from.has_trainreferencespeedcommand()) {
    trainreferencespeedcommand_ = new ::modes3::protobuf::TrainReferenceSpeedCommand(*from.trainreferencespeedcommand_);
  } else {
    trainreferencespeedcommand_ = NULL;
  }
  if (from.has_turnoutcommand()) {
    turnoutcommand_ = new ::modes3::protobuf::TurnoutCommand(*from.turnoutcommand_);
  } else {
    turnoutcommand_ = NULL;
  }
  if (from.has_turnoutstate()) {
    turnoutstate_ = new ::modes3::protobuf::TurnoutState(*from.turnoutstate_);
  } else {
    turnoutstate_ = NULL;
  }
  if (from.has_segmentoccupancy()) {
    segmentoccupancy_ = new ::modes3::protobuf::SegmentOccupancy(*from.segmentoccupancy_);
  } else {
    segmentoccupancy_ = NULL;
  }
  if (from.has_turnoutreferencestate()) {
    turnoutreferencestate_ = new ::modes3::protobuf::TurnoutReferenceState(*from.turnoutreferencestate_);
  } else {
    turnoutreferencestate_ = NULL;
  }
  if (from.has_dccoperationscommand()) {
    dccoperationscommand_ = new ::modes3::protobuf::DccOperationsCommand(*from.dccoperationscommand_);
  } else {
    dccoperationscommand_ = NULL;
  }
  if (from.has_dccoperationsstate()) {
    dccoperationsstate_ = new ::modes3::protobuf::DccOperationsState(*from.dccoperationsstate_);
  } else {
    dccoperationsstate_ = NULL;
  }
  if (from.has_allstatus()) {
    allstatus_ = new ::modes3::protobuf::SendAllStatus(*from.allstatus_);
  } else {
    allstatus_ = NULL;
  }
  if (from.has_computervisionobjectpositions()) {
    computervisionobjectpositions_ = new ::modes3::protobuf::ComputerVisionObjectPositions(*from.computervisionobjectpositions_);
  } else {
    computervisionobjectpositions_ = NULL;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:modes3.protobuf.Message)
}

void Message::SharedCtor() {
  ::memset(&segmentcommand_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&segmentcommand_)) + sizeof(type_));
  _cached_size_ = 0;
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:modes3.protobuf.Message)
  SharedDtor();
}

void Message::SharedDtor() {
  if (this != internal_default_instance()) delete segmentcommand_;
  if (this != internal_default_instance()) delete segmentstate_;
  if (this != internal_default_instance()) delete trainreferencespeed_;
  if (this != internal_default_instance()) delete trainreferencespeedcommand_;
  if (this != internal_default_instance()) delete turnoutcommand_;
  if (this != internal_default_instance()) delete turnoutstate_;
  if (this != internal_default_instance()) delete segmentoccupancy_;
  if (this != internal_default_instance()) delete turnoutreferencestate_;
  if (this != internal_default_instance()) delete dccoperationscommand_;
  if (this != internal_default_instance()) delete dccoperationsstate_;
  if (this != internal_default_instance()) delete allstatus_;
  if (this != internal_default_instance()) delete computervisionobjectpositions_;
}

void Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Message::descriptor() {
  protobuf_Message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Message& Message::default_instance() {
  protobuf_Message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Message* Message::New(::google::protobuf::Arena* arena) const {
  Message* n = new Message;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:modes3.protobuf.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && segmentcommand_ != NULL) {
    delete segmentcommand_;
  }
  segmentcommand_ = NULL;
  if (GetArenaNoVirtual() == NULL && segmentstate_ != NULL) {
    delete segmentstate_;
  }
  segmentstate_ = NULL;
  if (GetArenaNoVirtual() == NULL && trainreferencespeed_ != NULL) {
    delete trainreferencespeed_;
  }
  trainreferencespeed_ = NULL;
  if (GetArenaNoVirtual() == NULL && trainreferencespeedcommand_ != NULL) {
    delete trainreferencespeedcommand_;
  }
  trainreferencespeedcommand_ = NULL;
  if (GetArenaNoVirtual() == NULL && turnoutcommand_ != NULL) {
    delete turnoutcommand_;
  }
  turnoutcommand_ = NULL;
  if (GetArenaNoVirtual() == NULL && turnoutstate_ != NULL) {
    delete turnoutstate_;
  }
  turnoutstate_ = NULL;
  if (GetArenaNoVirtual() == NULL && segmentoccupancy_ != NULL) {
    delete segmentoccupancy_;
  }
  segmentoccupancy_ = NULL;
  if (GetArenaNoVirtual() == NULL && turnoutreferencestate_ != NULL) {
    delete turnoutreferencestate_;
  }
  turnoutreferencestate_ = NULL;
  if (GetArenaNoVirtual() == NULL && dccoperationscommand_ != NULL) {
    delete dccoperationscommand_;
  }
  dccoperationscommand_ = NULL;
  if (GetArenaNoVirtual() == NULL && dccoperationsstate_ != NULL) {
    delete dccoperationsstate_;
  }
  dccoperationsstate_ = NULL;
  if (GetArenaNoVirtual() == NULL && allstatus_ != NULL) {
    delete allstatus_;
  }
  allstatus_ = NULL;
  if (GetArenaNoVirtual() == NULL && computervisionobjectpositions_ != NULL) {
    delete computervisionobjectpositions_;
  }
  computervisionobjectpositions_ = NULL;
  type_ = 0;
  _internal_metadata_.Clear();
}

bool Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:modes3.protobuf.Message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .modes3.protobuf.MessageType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::modes3::protobuf::MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.SegmentCommand segmentCommand = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_segmentcommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.SegmentState segmentState = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_segmentstate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_trainreferencespeed()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_trainreferencespeedcommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.TurnoutCommand turnoutCommand = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_turnoutcommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.TurnoutState turnoutState = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_turnoutstate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.SegmentOccupancy segmentOccupancy = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_segmentoccupancy()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_turnoutreferencestate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dccoperationscommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.DccOperationsState dccOperationsState = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dccoperationsstate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.SendAllStatus allStatus = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_allstatus()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .modes3.protobuf.ComputerVisionObjectPositions computerVisionObjectPositions = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_computervisionobjectpositions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:modes3.protobuf.Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:modes3.protobuf.Message)
  return false;
#undef DO_
}

void Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:modes3.protobuf.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .modes3.protobuf.MessageType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .modes3.protobuf.SegmentCommand segmentCommand = 2;
  if (this->has_segmentcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->segmentcommand_, output);
  }

  // .modes3.protobuf.SegmentState segmentState = 3;
  if (this->has_segmentstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->segmentstate_, output);
  }

  // .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 4;
  if (this->has_trainreferencespeed()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->trainreferencespeed_, output);
  }

  // .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 5;
  if (this->has_trainreferencespeedcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->trainreferencespeedcommand_, output);
  }

  // .modes3.protobuf.TurnoutCommand turnoutCommand = 6;
  if (this->has_turnoutcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->turnoutcommand_, output);
  }

  // .modes3.protobuf.TurnoutState turnoutState = 7;
  if (this->has_turnoutstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->turnoutstate_, output);
  }

  // .modes3.protobuf.SegmentOccupancy segmentOccupancy = 8;
  if (this->has_segmentoccupancy()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->segmentoccupancy_, output);
  }

  // .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 9;
  if (this->has_turnoutreferencestate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->turnoutreferencestate_, output);
  }

  // .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 10;
  if (this->has_dccoperationscommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->dccoperationscommand_, output);
  }

  // .modes3.protobuf.DccOperationsState dccOperationsState = 11;
  if (this->has_dccoperationsstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->dccoperationsstate_, output);
  }

  // .modes3.protobuf.SendAllStatus allStatus = 12;
  if (this->has_allstatus()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->allstatus_, output);
  }

  // .modes3.protobuf.ComputerVisionObjectPositions computerVisionObjectPositions = 13;
  if (this->has_computervisionobjectpositions()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, *this->computervisionobjectpositions_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:modes3.protobuf.Message)
}

::google::protobuf::uint8* Message::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:modes3.protobuf.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .modes3.protobuf.MessageType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .modes3.protobuf.SegmentCommand segmentCommand = 2;
  if (this->has_segmentcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->segmentcommand_, deterministic, target);
  }

  // .modes3.protobuf.SegmentState segmentState = 3;
  if (this->has_segmentstate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->segmentstate_, deterministic, target);
  }

  // .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 4;
  if (this->has_trainreferencespeed()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->trainreferencespeed_, deterministic, target);
  }

  // .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 5;
  if (this->has_trainreferencespeedcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->trainreferencespeedcommand_, deterministic, target);
  }

  // .modes3.protobuf.TurnoutCommand turnoutCommand = 6;
  if (this->has_turnoutcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->turnoutcommand_, deterministic, target);
  }

  // .modes3.protobuf.TurnoutState turnoutState = 7;
  if (this->has_turnoutstate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->turnoutstate_, deterministic, target);
  }

  // .modes3.protobuf.SegmentOccupancy segmentOccupancy = 8;
  if (this->has_segmentoccupancy()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        8, *this->segmentoccupancy_, deterministic, target);
  }

  // .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 9;
  if (this->has_turnoutreferencestate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        9, *this->turnoutreferencestate_, deterministic, target);
  }

  // .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 10;
  if (this->has_dccoperationscommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, *this->dccoperationscommand_, deterministic, target);
  }

  // .modes3.protobuf.DccOperationsState dccOperationsState = 11;
  if (this->has_dccoperationsstate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, *this->dccoperationsstate_, deterministic, target);
  }

  // .modes3.protobuf.SendAllStatus allStatus = 12;
  if (this->has_allstatus()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *this->allstatus_, deterministic, target);
  }

  // .modes3.protobuf.ComputerVisionObjectPositions computerVisionObjectPositions = 13;
  if (this->has_computervisionobjectpositions()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        13, *this->computervisionobjectpositions_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modes3.protobuf.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modes3.protobuf.Message)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .modes3.protobuf.SegmentCommand segmentCommand = 2;
  if (this->has_segmentcommand()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->segmentcommand_);
  }

  // .modes3.protobuf.SegmentState segmentState = 3;
  if (this->has_segmentstate()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->segmentstate_);
  }

  // .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 4;
  if (this->has_trainreferencespeed()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->trainreferencespeed_);
  }

  // .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 5;
  if (this->has_trainreferencespeedcommand()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->trainreferencespeedcommand_);
  }

  // .modes3.protobuf.TurnoutCommand turnoutCommand = 6;
  if (this->has_turnoutcommand()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->turnoutcommand_);
  }

  // .modes3.protobuf.TurnoutState turnoutState = 7;
  if (this->has_turnoutstate()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->turnoutstate_);
  }

  // .modes3.protobuf.SegmentOccupancy segmentOccupancy = 8;
  if (this->has_segmentoccupancy()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->segmentoccupancy_);
  }

  // .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 9;
  if (this->has_turnoutreferencestate()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->turnoutreferencestate_);
  }

  // .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 10;
  if (this->has_dccoperationscommand()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->dccoperationscommand_);
  }

  // .modes3.protobuf.DccOperationsState dccOperationsState = 11;
  if (this->has_dccoperationsstate()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->dccoperationsstate_);
  }

  // .modes3.protobuf.SendAllStatus allStatus = 12;
  if (this->has_allstatus()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->allstatus_);
  }

  // .modes3.protobuf.ComputerVisionObjectPositions computerVisionObjectPositions = 13;
  if (this->has_computervisionobjectpositions()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->computervisionobjectpositions_);
  }

  // .modes3.protobuf.MessageType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:modes3.protobuf.Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Message* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Message>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:modes3.protobuf.Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:modes3.protobuf.Message)
    MergeFrom(*source);
  }
}

void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:modes3.protobuf.Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_segmentcommand()) {
    mutable_segmentcommand()->::modes3::protobuf::SegmentCommand::MergeFrom(from.segmentcommand());
  }
  if (from.has_segmentstate()) {
    mutable_segmentstate()->::modes3::protobuf::SegmentState::MergeFrom(from.segmentstate());
  }
  if (from.has_trainreferencespeed()) {
    mutable_trainreferencespeed()->::modes3::protobuf::TrainReferenceSpeed::MergeFrom(from.trainreferencespeed());
  }
  if (from.has_trainreferencespeedcommand()) {
    mutable_trainreferencespeedcommand()->::modes3::protobuf::TrainReferenceSpeedCommand::MergeFrom(from.trainreferencespeedcommand());
  }
  if (from.has_turnoutcommand()) {
    mutable_turnoutcommand()->::modes3::protobuf::TurnoutCommand::MergeFrom(from.turnoutcommand());
  }
  if (from.has_turnoutstate()) {
    mutable_turnoutstate()->::modes3::protobuf::TurnoutState::MergeFrom(from.turnoutstate());
  }
  if (from.has_segmentoccupancy()) {
    mutable_segmentoccupancy()->::modes3::protobuf::SegmentOccupancy::MergeFrom(from.segmentoccupancy());
  }
  if (from.has_turnoutreferencestate()) {
    mutable_turnoutreferencestate()->::modes3::protobuf::TurnoutReferenceState::MergeFrom(from.turnoutreferencestate());
  }
  if (from.has_dccoperationscommand()) {
    mutable_dccoperationscommand()->::modes3::protobuf::DccOperationsCommand::MergeFrom(from.dccoperationscommand());
  }
  if (from.has_dccoperationsstate()) {
    mutable_dccoperationsstate()->::modes3::protobuf::DccOperationsState::MergeFrom(from.dccoperationsstate());
  }
  if (from.has_allstatus()) {
    mutable_allstatus()->::modes3::protobuf::SendAllStatus::MergeFrom(from.allstatus());
  }
  if (from.has_computervisionobjectpositions()) {
    mutable_computervisionobjectpositions()->::modes3::protobuf::ComputerVisionObjectPositions::MergeFrom(from.computervisionobjectpositions());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:modes3.protobuf.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modes3.protobuf.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::Swap(Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Message::InternalSwap(Message* other) {
  using std::swap;
  swap(segmentcommand_, other->segmentcommand_);
  swap(segmentstate_, other->segmentstate_);
  swap(trainreferencespeed_, other->trainreferencespeed_);
  swap(trainreferencespeedcommand_, other->trainreferencespeedcommand_);
  swap(turnoutcommand_, other->turnoutcommand_);
  swap(turnoutstate_, other->turnoutstate_);
  swap(segmentoccupancy_, other->segmentoccupancy_);
  swap(turnoutreferencestate_, other->turnoutreferencestate_);
  swap(dccoperationscommand_, other->dccoperationscommand_);
  swap(dccoperationsstate_, other->dccoperationsstate_);
  swap(allstatus_, other->allstatus_);
  swap(computervisionobjectpositions_, other->computervisionobjectpositions_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Message::GetMetadata() const {
  protobuf_Message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// .modes3.protobuf.MessageType type = 1;
void Message::clear_type() {
  type_ = 0;
}
::modes3::protobuf::MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.type)
  return static_cast< ::modes3::protobuf::MessageType >(type_);
}
void Message::set_type(::modes3::protobuf::MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.Message.type)
}

// .modes3.protobuf.SegmentCommand segmentCommand = 2;
bool Message::has_segmentcommand() const {
  return this != internal_default_instance() && segmentcommand_ != NULL;
}
void Message::clear_segmentcommand() {
  if (GetArenaNoVirtual() == NULL && segmentcommand_ != NULL) delete segmentcommand_;
  segmentcommand_ = NULL;
}
const ::modes3::protobuf::SegmentCommand& Message::segmentcommand() const {
  const ::modes3::protobuf::SegmentCommand* p = segmentcommand_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.segmentCommand)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::SegmentCommand*>(
      &::modes3::protobuf::_SegmentCommand_default_instance_);
}
::modes3::protobuf::SegmentCommand* Message::mutable_segmentcommand() {
  
  if (segmentcommand_ == NULL) {
    segmentcommand_ = new ::modes3::protobuf::SegmentCommand;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.segmentCommand)
  return segmentcommand_;
}
::modes3::protobuf::SegmentCommand* Message::release_segmentcommand() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.segmentCommand)
  
  ::modes3::protobuf::SegmentCommand* temp = segmentcommand_;
  segmentcommand_ = NULL;
  return temp;
}
void Message::set_allocated_segmentcommand(::modes3::protobuf::SegmentCommand* segmentcommand) {
  delete segmentcommand_;
  segmentcommand_ = segmentcommand;
  if (segmentcommand) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.segmentCommand)
}

// .modes3.protobuf.SegmentState segmentState = 3;
bool Message::has_segmentstate() const {
  return this != internal_default_instance() && segmentstate_ != NULL;
}
void Message::clear_segmentstate() {
  if (GetArenaNoVirtual() == NULL && segmentstate_ != NULL) delete segmentstate_;
  segmentstate_ = NULL;
}
const ::modes3::protobuf::SegmentState& Message::segmentstate() const {
  const ::modes3::protobuf::SegmentState* p = segmentstate_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.segmentState)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::SegmentState*>(
      &::modes3::protobuf::_SegmentState_default_instance_);
}
::modes3::protobuf::SegmentState* Message::mutable_segmentstate() {
  
  if (segmentstate_ == NULL) {
    segmentstate_ = new ::modes3::protobuf::SegmentState;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.segmentState)
  return segmentstate_;
}
::modes3::protobuf::SegmentState* Message::release_segmentstate() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.segmentState)
  
  ::modes3::protobuf::SegmentState* temp = segmentstate_;
  segmentstate_ = NULL;
  return temp;
}
void Message::set_allocated_segmentstate(::modes3::protobuf::SegmentState* segmentstate) {
  delete segmentstate_;
  segmentstate_ = segmentstate;
  if (segmentstate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.segmentState)
}

// .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 4;
bool Message::has_trainreferencespeed() const {
  return this != internal_default_instance() && trainreferencespeed_ != NULL;
}
void Message::clear_trainreferencespeed() {
  if (GetArenaNoVirtual() == NULL && trainreferencespeed_ != NULL) delete trainreferencespeed_;
  trainreferencespeed_ = NULL;
}
const ::modes3::protobuf::TrainReferenceSpeed& Message::trainreferencespeed() const {
  const ::modes3::protobuf::TrainReferenceSpeed* p = trainreferencespeed_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.trainReferenceSpeed)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::TrainReferenceSpeed*>(
      &::modes3::protobuf::_TrainReferenceSpeed_default_instance_);
}
::modes3::protobuf::TrainReferenceSpeed* Message::mutable_trainreferencespeed() {
  
  if (trainreferencespeed_ == NULL) {
    trainreferencespeed_ = new ::modes3::protobuf::TrainReferenceSpeed;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.trainReferenceSpeed)
  return trainreferencespeed_;
}
::modes3::protobuf::TrainReferenceSpeed* Message::release_trainreferencespeed() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.trainReferenceSpeed)
  
  ::modes3::protobuf::TrainReferenceSpeed* temp = trainreferencespeed_;
  trainreferencespeed_ = NULL;
  return temp;
}
void Message::set_allocated_trainreferencespeed(::modes3::protobuf::TrainReferenceSpeed* trainreferencespeed) {
  delete trainreferencespeed_;
  trainreferencespeed_ = trainreferencespeed;
  if (trainreferencespeed) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.trainReferenceSpeed)
}

// .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 5;
bool Message::has_trainreferencespeedcommand() const {
  return this != internal_default_instance() && trainreferencespeedcommand_ != NULL;
}
void Message::clear_trainreferencespeedcommand() {
  if (GetArenaNoVirtual() == NULL && trainreferencespeedcommand_ != NULL) delete trainreferencespeedcommand_;
  trainreferencespeedcommand_ = NULL;
}
const ::modes3::protobuf::TrainReferenceSpeedCommand& Message::trainreferencespeedcommand() const {
  const ::modes3::protobuf::TrainReferenceSpeedCommand* p = trainreferencespeedcommand_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.trainReferenceSpeedCommand)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::TrainReferenceSpeedCommand*>(
      &::modes3::protobuf::_TrainReferenceSpeedCommand_default_instance_);
}
::modes3::protobuf::TrainReferenceSpeedCommand* Message::mutable_trainreferencespeedcommand() {
  
  if (trainreferencespeedcommand_ == NULL) {
    trainreferencespeedcommand_ = new ::modes3::protobuf::TrainReferenceSpeedCommand;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.trainReferenceSpeedCommand)
  return trainreferencespeedcommand_;
}
::modes3::protobuf::TrainReferenceSpeedCommand* Message::release_trainreferencespeedcommand() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.trainReferenceSpeedCommand)
  
  ::modes3::protobuf::TrainReferenceSpeedCommand* temp = trainreferencespeedcommand_;
  trainreferencespeedcommand_ = NULL;
  return temp;
}
void Message::set_allocated_trainreferencespeedcommand(::modes3::protobuf::TrainReferenceSpeedCommand* trainreferencespeedcommand) {
  delete trainreferencespeedcommand_;
  trainreferencespeedcommand_ = trainreferencespeedcommand;
  if (trainreferencespeedcommand) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.trainReferenceSpeedCommand)
}

// .modes3.protobuf.TurnoutCommand turnoutCommand = 6;
bool Message::has_turnoutcommand() const {
  return this != internal_default_instance() && turnoutcommand_ != NULL;
}
void Message::clear_turnoutcommand() {
  if (GetArenaNoVirtual() == NULL && turnoutcommand_ != NULL) delete turnoutcommand_;
  turnoutcommand_ = NULL;
}
const ::modes3::protobuf::TurnoutCommand& Message::turnoutcommand() const {
  const ::modes3::protobuf::TurnoutCommand* p = turnoutcommand_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.turnoutCommand)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::TurnoutCommand*>(
      &::modes3::protobuf::_TurnoutCommand_default_instance_);
}
::modes3::protobuf::TurnoutCommand* Message::mutable_turnoutcommand() {
  
  if (turnoutcommand_ == NULL) {
    turnoutcommand_ = new ::modes3::protobuf::TurnoutCommand;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.turnoutCommand)
  return turnoutcommand_;
}
::modes3::protobuf::TurnoutCommand* Message::release_turnoutcommand() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.turnoutCommand)
  
  ::modes3::protobuf::TurnoutCommand* temp = turnoutcommand_;
  turnoutcommand_ = NULL;
  return temp;
}
void Message::set_allocated_turnoutcommand(::modes3::protobuf::TurnoutCommand* turnoutcommand) {
  delete turnoutcommand_;
  turnoutcommand_ = turnoutcommand;
  if (turnoutcommand) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.turnoutCommand)
}

// .modes3.protobuf.TurnoutState turnoutState = 7;
bool Message::has_turnoutstate() const {
  return this != internal_default_instance() && turnoutstate_ != NULL;
}
void Message::clear_turnoutstate() {
  if (GetArenaNoVirtual() == NULL && turnoutstate_ != NULL) delete turnoutstate_;
  turnoutstate_ = NULL;
}
const ::modes3::protobuf::TurnoutState& Message::turnoutstate() const {
  const ::modes3::protobuf::TurnoutState* p = turnoutstate_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.turnoutState)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::TurnoutState*>(
      &::modes3::protobuf::_TurnoutState_default_instance_);
}
::modes3::protobuf::TurnoutState* Message::mutable_turnoutstate() {
  
  if (turnoutstate_ == NULL) {
    turnoutstate_ = new ::modes3::protobuf::TurnoutState;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.turnoutState)
  return turnoutstate_;
}
::modes3::protobuf::TurnoutState* Message::release_turnoutstate() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.turnoutState)
  
  ::modes3::protobuf::TurnoutState* temp = turnoutstate_;
  turnoutstate_ = NULL;
  return temp;
}
void Message::set_allocated_turnoutstate(::modes3::protobuf::TurnoutState* turnoutstate) {
  delete turnoutstate_;
  turnoutstate_ = turnoutstate;
  if (turnoutstate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.turnoutState)
}

// .modes3.protobuf.SegmentOccupancy segmentOccupancy = 8;
bool Message::has_segmentoccupancy() const {
  return this != internal_default_instance() && segmentoccupancy_ != NULL;
}
void Message::clear_segmentoccupancy() {
  if (GetArenaNoVirtual() == NULL && segmentoccupancy_ != NULL) delete segmentoccupancy_;
  segmentoccupancy_ = NULL;
}
const ::modes3::protobuf::SegmentOccupancy& Message::segmentoccupancy() const {
  const ::modes3::protobuf::SegmentOccupancy* p = segmentoccupancy_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.segmentOccupancy)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::SegmentOccupancy*>(
      &::modes3::protobuf::_SegmentOccupancy_default_instance_);
}
::modes3::protobuf::SegmentOccupancy* Message::mutable_segmentoccupancy() {
  
  if (segmentoccupancy_ == NULL) {
    segmentoccupancy_ = new ::modes3::protobuf::SegmentOccupancy;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.segmentOccupancy)
  return segmentoccupancy_;
}
::modes3::protobuf::SegmentOccupancy* Message::release_segmentoccupancy() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.segmentOccupancy)
  
  ::modes3::protobuf::SegmentOccupancy* temp = segmentoccupancy_;
  segmentoccupancy_ = NULL;
  return temp;
}
void Message::set_allocated_segmentoccupancy(::modes3::protobuf::SegmentOccupancy* segmentoccupancy) {
  delete segmentoccupancy_;
  segmentoccupancy_ = segmentoccupancy;
  if (segmentoccupancy) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.segmentOccupancy)
}

// .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 9;
bool Message::has_turnoutreferencestate() const {
  return this != internal_default_instance() && turnoutreferencestate_ != NULL;
}
void Message::clear_turnoutreferencestate() {
  if (GetArenaNoVirtual() == NULL && turnoutreferencestate_ != NULL) delete turnoutreferencestate_;
  turnoutreferencestate_ = NULL;
}
const ::modes3::protobuf::TurnoutReferenceState& Message::turnoutreferencestate() const {
  const ::modes3::protobuf::TurnoutReferenceState* p = turnoutreferencestate_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.turnoutReferenceState)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::TurnoutReferenceState*>(
      &::modes3::protobuf::_TurnoutReferenceState_default_instance_);
}
::modes3::protobuf::TurnoutReferenceState* Message::mutable_turnoutreferencestate() {
  
  if (turnoutreferencestate_ == NULL) {
    turnoutreferencestate_ = new ::modes3::protobuf::TurnoutReferenceState;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.turnoutReferenceState)
  return turnoutreferencestate_;
}
::modes3::protobuf::TurnoutReferenceState* Message::release_turnoutreferencestate() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.turnoutReferenceState)
  
  ::modes3::protobuf::TurnoutReferenceState* temp = turnoutreferencestate_;
  turnoutreferencestate_ = NULL;
  return temp;
}
void Message::set_allocated_turnoutreferencestate(::modes3::protobuf::TurnoutReferenceState* turnoutreferencestate) {
  delete turnoutreferencestate_;
  turnoutreferencestate_ = turnoutreferencestate;
  if (turnoutreferencestate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.turnoutReferenceState)
}

// .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 10;
bool Message::has_dccoperationscommand() const {
  return this != internal_default_instance() && dccoperationscommand_ != NULL;
}
void Message::clear_dccoperationscommand() {
  if (GetArenaNoVirtual() == NULL && dccoperationscommand_ != NULL) delete dccoperationscommand_;
  dccoperationscommand_ = NULL;
}
const ::modes3::protobuf::DccOperationsCommand& Message::dccoperationscommand() const {
  const ::modes3::protobuf::DccOperationsCommand* p = dccoperationscommand_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.dccOperationsCommand)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::DccOperationsCommand*>(
      &::modes3::protobuf::_DccOperationsCommand_default_instance_);
}
::modes3::protobuf::DccOperationsCommand* Message::mutable_dccoperationscommand() {
  
  if (dccoperationscommand_ == NULL) {
    dccoperationscommand_ = new ::modes3::protobuf::DccOperationsCommand;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.dccOperationsCommand)
  return dccoperationscommand_;
}
::modes3::protobuf::DccOperationsCommand* Message::release_dccoperationscommand() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.dccOperationsCommand)
  
  ::modes3::protobuf::DccOperationsCommand* temp = dccoperationscommand_;
  dccoperationscommand_ = NULL;
  return temp;
}
void Message::set_allocated_dccoperationscommand(::modes3::protobuf::DccOperationsCommand* dccoperationscommand) {
  delete dccoperationscommand_;
  dccoperationscommand_ = dccoperationscommand;
  if (dccoperationscommand) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.dccOperationsCommand)
}

// .modes3.protobuf.DccOperationsState dccOperationsState = 11;
bool Message::has_dccoperationsstate() const {
  return this != internal_default_instance() && dccoperationsstate_ != NULL;
}
void Message::clear_dccoperationsstate() {
  if (GetArenaNoVirtual() == NULL && dccoperationsstate_ != NULL) delete dccoperationsstate_;
  dccoperationsstate_ = NULL;
}
const ::modes3::protobuf::DccOperationsState& Message::dccoperationsstate() const {
  const ::modes3::protobuf::DccOperationsState* p = dccoperationsstate_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.dccOperationsState)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::DccOperationsState*>(
      &::modes3::protobuf::_DccOperationsState_default_instance_);
}
::modes3::protobuf::DccOperationsState* Message::mutable_dccoperationsstate() {
  
  if (dccoperationsstate_ == NULL) {
    dccoperationsstate_ = new ::modes3::protobuf::DccOperationsState;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.dccOperationsState)
  return dccoperationsstate_;
}
::modes3::protobuf::DccOperationsState* Message::release_dccoperationsstate() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.dccOperationsState)
  
  ::modes3::protobuf::DccOperationsState* temp = dccoperationsstate_;
  dccoperationsstate_ = NULL;
  return temp;
}
void Message::set_allocated_dccoperationsstate(::modes3::protobuf::DccOperationsState* dccoperationsstate) {
  delete dccoperationsstate_;
  dccoperationsstate_ = dccoperationsstate;
  if (dccoperationsstate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.dccOperationsState)
}

// .modes3.protobuf.SendAllStatus allStatus = 12;
bool Message::has_allstatus() const {
  return this != internal_default_instance() && allstatus_ != NULL;
}
void Message::clear_allstatus() {
  if (GetArenaNoVirtual() == NULL && allstatus_ != NULL) delete allstatus_;
  allstatus_ = NULL;
}
const ::modes3::protobuf::SendAllStatus& Message::allstatus() const {
  const ::modes3::protobuf::SendAllStatus* p = allstatus_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.allStatus)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::SendAllStatus*>(
      &::modes3::protobuf::_SendAllStatus_default_instance_);
}
::modes3::protobuf::SendAllStatus* Message::mutable_allstatus() {
  
  if (allstatus_ == NULL) {
    allstatus_ = new ::modes3::protobuf::SendAllStatus;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.allStatus)
  return allstatus_;
}
::modes3::protobuf::SendAllStatus* Message::release_allstatus() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.allStatus)
  
  ::modes3::protobuf::SendAllStatus* temp = allstatus_;
  allstatus_ = NULL;
  return temp;
}
void Message::set_allocated_allstatus(::modes3::protobuf::SendAllStatus* allstatus) {
  delete allstatus_;
  allstatus_ = allstatus;
  if (allstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.allStatus)
}

// .modes3.protobuf.ComputerVisionObjectPositions computerVisionObjectPositions = 13;
bool Message::has_computervisionobjectpositions() const {
  return this != internal_default_instance() && computervisionobjectpositions_ != NULL;
}
void Message::clear_computervisionobjectpositions() {
  if (GetArenaNoVirtual() == NULL && computervisionobjectpositions_ != NULL) delete computervisionobjectpositions_;
  computervisionobjectpositions_ = NULL;
}
const ::modes3::protobuf::ComputerVisionObjectPositions& Message::computervisionobjectpositions() const {
  const ::modes3::protobuf::ComputerVisionObjectPositions* p = computervisionobjectpositions_;
  // @@protoc_insertion_point(field_get:modes3.protobuf.Message.computerVisionObjectPositions)
  return p != NULL ? *p : *reinterpret_cast<const ::modes3::protobuf::ComputerVisionObjectPositions*>(
      &::modes3::protobuf::_ComputerVisionObjectPositions_default_instance_);
}
::modes3::protobuf::ComputerVisionObjectPositions* Message::mutable_computervisionobjectpositions() {
  
  if (computervisionobjectpositions_ == NULL) {
    computervisionobjectpositions_ = new ::modes3::protobuf::ComputerVisionObjectPositions;
  }
  // @@protoc_insertion_point(field_mutable:modes3.protobuf.Message.computerVisionObjectPositions)
  return computervisionobjectpositions_;
}
::modes3::protobuf::ComputerVisionObjectPositions* Message::release_computervisionobjectpositions() {
  // @@protoc_insertion_point(field_release:modes3.protobuf.Message.computerVisionObjectPositions)
  
  ::modes3::protobuf::ComputerVisionObjectPositions* temp = computervisionobjectpositions_;
  computervisionobjectpositions_ = NULL;
  return temp;
}
void Message::set_allocated_computervisionobjectpositions(::modes3::protobuf::ComputerVisionObjectPositions* computervisionobjectpositions) {
  delete computervisionobjectpositions_;
  computervisionobjectpositions_ = computervisionobjectpositions;
  if (computervisionobjectpositions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:modes3.protobuf.Message.computerVisionObjectPositions)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace modes3

// @@protoc_insertion_point(global_scope)
