// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainFunctionState.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TrainFunctionState.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace modes3 {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* TrainFunctionState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrainFunctionState_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TrainFunctionState_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_TrainFunctionState_2eproto() {
  protobuf_AddDesc_TrainFunctionState_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TrainFunctionState.proto");
  GOOGLE_CHECK(file != NULL);
  TrainFunctionState_descriptor_ = file->message_type(0);
  static const int TrainFunctionState_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainFunctionState, trainid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainFunctionState, functionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainFunctionState, trainfunctionvalue_),
  };
  TrainFunctionState_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TrainFunctionState_descriptor_,
      TrainFunctionState::internal_default_instance(),
      TrainFunctionState_offsets_,
      -1,
      -1,
      -1,
      sizeof(TrainFunctionState),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainFunctionState, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TrainFunctionState_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TrainFunctionState_descriptor_, TrainFunctionState::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TrainFunctionState_2eproto() {
  TrainFunctionState_default_instance_.Shutdown();
  delete TrainFunctionState_reflection_;
}

void protobuf_InitDefaults_TrainFunctionState_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::modes3::protobuf::protobuf_InitDefaults_Enums_2eproto();
  TrainFunctionState_default_instance_.DefaultConstruct();
  TrainFunctionState_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_TrainFunctionState_2eproto_once_);
void protobuf_InitDefaults_TrainFunctionState_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_TrainFunctionState_2eproto_once_,
                 &protobuf_InitDefaults_TrainFunctionState_2eproto_impl);
}
void protobuf_AddDesc_TrainFunctionState_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_TrainFunctionState_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030TrainFunctionState.proto\022\017modes3.proto"
    "buf\032\013Enums.proto\"z\n\022TrainFunctionState\022\017"
    "\n\007trainID\030\001 \001(\r\022\022\n\nfunctionID\030\002 \001(\r\022\?\n\022t"
    "rainFunctionValue\030\003 \001(\0162#.modes3.protobu"
    "f.TrainFunctionValueB0\n,hu.bme.mit.inf.m"
    "odes3.messaging.mms.messagesP\001b\006proto3", 238);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TrainFunctionState.proto", &protobuf_RegisterTypes);
  ::modes3::protobuf::protobuf_AddDesc_Enums_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TrainFunctionState_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_TrainFunctionState_2eproto_once_);
void protobuf_AddDesc_TrainFunctionState_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_TrainFunctionState_2eproto_once_,
                 &protobuf_AddDesc_TrainFunctionState_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TrainFunctionState_2eproto {
  StaticDescriptorInitializer_TrainFunctionState_2eproto() {
    protobuf_AddDesc_TrainFunctionState_2eproto();
  }
} static_descriptor_initializer_TrainFunctionState_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TrainFunctionState::kTrainIDFieldNumber;
const int TrainFunctionState::kFunctionIDFieldNumber;
const int TrainFunctionState::kTrainFunctionValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TrainFunctionState::TrainFunctionState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_TrainFunctionState_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:modes3.protobuf.TrainFunctionState)
}

void TrainFunctionState::InitAsDefaultInstance() {
}

TrainFunctionState::TrainFunctionState(const TrainFunctionState& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:modes3.protobuf.TrainFunctionState)
}

void TrainFunctionState::SharedCtor() {
  ::memset(&trainid_, 0, reinterpret_cast<char*>(&trainfunctionvalue_) -
    reinterpret_cast<char*>(&trainid_) + sizeof(trainfunctionvalue_));
  _cached_size_ = 0;
}

TrainFunctionState::~TrainFunctionState() {
  // @@protoc_insertion_point(destructor:modes3.protobuf.TrainFunctionState)
  SharedDtor();
}

void TrainFunctionState::SharedDtor() {
}

void TrainFunctionState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TrainFunctionState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrainFunctionState_descriptor_;
}

const TrainFunctionState& TrainFunctionState::default_instance() {
  protobuf_InitDefaults_TrainFunctionState_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TrainFunctionState> TrainFunctionState_default_instance_;

TrainFunctionState* TrainFunctionState::New(::google::protobuf::Arena* arena) const {
  TrainFunctionState* n = new TrainFunctionState;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TrainFunctionState::Clear() {
// @@protoc_insertion_point(message_clear_start:modes3.protobuf.TrainFunctionState)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(TrainFunctionState, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TrainFunctionState*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(trainid_, trainfunctionvalue_);

#undef ZR_HELPER_
#undef ZR_

}

bool TrainFunctionState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:modes3.protobuf.TrainFunctionState)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 trainID = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trainid_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_functionID;
        break;
      }

      // optional uint32 functionID = 2;
      case 2: {
        if (tag == 16) {
         parse_functionID:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &functionid_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_trainFunctionValue;
        break;
      }

      // optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;
      case 3: {
        if (tag == 24) {
         parse_trainFunctionValue:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_trainfunctionvalue(static_cast< ::modes3::protobuf::TrainFunctionValue >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:modes3.protobuf.TrainFunctionState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:modes3.protobuf.TrainFunctionState)
  return false;
#undef DO_
}

void TrainFunctionState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:modes3.protobuf.TrainFunctionState)
  // optional uint32 trainID = 1;
  if (this->trainid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->trainid(), output);
  }

  // optional uint32 functionID = 2;
  if (this->functionid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->functionid(), output);
  }

  // optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;
  if (this->trainfunctionvalue() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->trainfunctionvalue(), output);
  }

  // @@protoc_insertion_point(serialize_end:modes3.protobuf.TrainFunctionState)
}

::google::protobuf::uint8* TrainFunctionState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:modes3.protobuf.TrainFunctionState)
  // optional uint32 trainID = 1;
  if (this->trainid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->trainid(), target);
  }

  // optional uint32 functionID = 2;
  if (this->functionid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->functionid(), target);
  }

  // optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;
  if (this->trainfunctionvalue() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->trainfunctionvalue(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:modes3.protobuf.TrainFunctionState)
  return target;
}

size_t TrainFunctionState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modes3.protobuf.TrainFunctionState)
  size_t total_size = 0;

  // optional uint32 trainID = 1;
  if (this->trainid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->trainid());
  }

  // optional uint32 functionID = 2;
  if (this->functionid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->functionid());
  }

  // optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;
  if (this->trainfunctionvalue() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->trainfunctionvalue());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TrainFunctionState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:modes3.protobuf.TrainFunctionState)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TrainFunctionState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TrainFunctionState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:modes3.protobuf.TrainFunctionState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:modes3.protobuf.TrainFunctionState)
    UnsafeMergeFrom(*source);
  }
}

void TrainFunctionState::MergeFrom(const TrainFunctionState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:modes3.protobuf.TrainFunctionState)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void TrainFunctionState::UnsafeMergeFrom(const TrainFunctionState& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.trainid() != 0) {
    set_trainid(from.trainid());
  }
  if (from.functionid() != 0) {
    set_functionid(from.functionid());
  }
  if (from.trainfunctionvalue() != 0) {
    set_trainfunctionvalue(from.trainfunctionvalue());
  }
}

void TrainFunctionState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:modes3.protobuf.TrainFunctionState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrainFunctionState::CopyFrom(const TrainFunctionState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modes3.protobuf.TrainFunctionState)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool TrainFunctionState::IsInitialized() const {

  return true;
}

void TrainFunctionState::Swap(TrainFunctionState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TrainFunctionState::InternalSwap(TrainFunctionState* other) {
  std::swap(trainid_, other->trainid_);
  std::swap(functionid_, other->functionid_);
  std::swap(trainfunctionvalue_, other->trainfunctionvalue_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TrainFunctionState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TrainFunctionState_descriptor_;
  metadata.reflection = TrainFunctionState_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TrainFunctionState

// optional uint32 trainID = 1;
void TrainFunctionState::clear_trainid() {
  trainid_ = 0u;
}
::google::protobuf::uint32 TrainFunctionState::trainid() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.TrainFunctionState.trainID)
  return trainid_;
}
void TrainFunctionState::set_trainid(::google::protobuf::uint32 value) {
  
  trainid_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.TrainFunctionState.trainID)
}

// optional uint32 functionID = 2;
void TrainFunctionState::clear_functionid() {
  functionid_ = 0u;
}
::google::protobuf::uint32 TrainFunctionState::functionid() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.TrainFunctionState.functionID)
  return functionid_;
}
void TrainFunctionState::set_functionid(::google::protobuf::uint32 value) {
  
  functionid_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.TrainFunctionState.functionID)
}

// optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;
void TrainFunctionState::clear_trainfunctionvalue() {
  trainfunctionvalue_ = 0;
}
::modes3::protobuf::TrainFunctionValue TrainFunctionState::trainfunctionvalue() const {
  // @@protoc_insertion_point(field_get:modes3.protobuf.TrainFunctionState.trainFunctionValue)
  return static_cast< ::modes3::protobuf::TrainFunctionValue >(trainfunctionvalue_);
}
void TrainFunctionState::set_trainfunctionvalue(::modes3::protobuf::TrainFunctionValue value) {
  
  trainfunctionvalue_ = value;
  // @@protoc_insertion_point(field_set:modes3.protobuf.TrainFunctionState.trainFunctionValue)
}

inline const TrainFunctionState* TrainFunctionState::internal_default_instance() {
  return &TrainFunctionState_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace modes3

// @@protoc_insertion_point(global_scope)
