language: java
jdk:
  - oraclejdk8
branches:
  only:
    - gen3-arch
addons:
  apt:
    packages:
      - libzmq3-dev
before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.4.1/git-lfs-linux-amd64-1.4.1.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.4.1.tar.gz
  - mv git-lfs-1.4.1/git-lfs $HOME/git-lfs
  - export PATH=$PATH:$HOME/
install: false
before_script:
  - git lfs pull
script:
  - cd src/java
  - ./gradlew wrapper
  - ./gradlew build -x test || ./gradlew build -x test || ./gradlew build -x test
  - ./gradlew check
cache:
  directories:
    - $HOME/.gradle/wrapper/
notifications:
  slack: ftsrg:WZdZQP5KHhnxklapMmjNEe3I
