/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.inf.parametricTimedRegularExpression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.inf.parametricTimedRegularExpression.ParametricTimedRegularExpressionPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
