#!/bin/bash

division=(50 66 75 80 83 85 88 90)
COMMANDS=("dashboard" "xpressnetbridge" "occupancyquerier")
startindex=0
let "startindex = ${#COMMANDS[@]}-5"
SESSIONNAME="rpimanager"
target="192.168.1.4"

tmux has-session -t $SESSIONNAME &> /dev/null
if [ $? != 0 ]
then
    	echo "Creating manager session"
    	tmux new-session -s $SESSIONNAME -d

	# creating columns
	tmux split-window -h -p 66 -t 0
	tmux split-window -h -p 50 -t 1

	# the layout will be:
	#
	# .----------,-----------,-----------,...,
	# |          |           |           |   |
	# |    0     |     1     |     2     |   |
	# |          |           |           |   |
	# '----------'-----------'-----------'...

	while [ $startindex -ge 0 ]
	do
		# creating row
		div=${division[$startindex]}
		tmux split-window -h -p $div -t 0
		let "startindex -= 1"
	done

	index=0
	for command in ${COMMANDS[@]}
	do
		# sending ssh login to every pane
		tmux send-keys -t  $index "ssh pi@$target" Enter
		
		let "index += 1"
	done
		
	# make some delay to make sure every ssh on the logging in phase
	sleep 1 #s

	index=0
	for command in ${COMMANDS[@]}
	do
		# sending ssh login to every pane
		tmux send-keys -t  $index "raspberry" Enter
		
		let "index += 1"
	done

	# wait again to logging in
	sleep 1 # s

	index=0
	for command in ${COMMANDS[@]}
	do
		# sending command for every pane
		tmux send-keys -t  $index $command Enter
		sleep 1 # s
		
		let "index += 1"
	done
		
fi

tmux attach -t $SESSIONNAME
