/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.inf.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractParametricTimedRegularExpressionValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(hu.bme.mit.inf.parametricTimedRegularExpression.ParametricTimedRegularExpressionPackage.eINSTANCE);
		return result;
	}
	
}
