---
- name: Copy the new systemd unit
  copy:
    src: "{{playbook_dir}}/files/modes3-{{service_name}}.service"
    dest: "/etc/systemd/system/modes3-{{service_name}}.service"
    mode: 0644
    force: yes
  become: true
- name: Enable and start the service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: "modes3-{{service_name}}"
  become: true