<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="railroadmodel" nsURI="http://hu.bme.mit.kv.railroadmodel" nsPrefix="railroadmodel">
  <eClassifiers xsi:type="ecore:EClass" name="TrainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyOn" lowerBound="1"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goingClockwise" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clockwise" lowerBound="1"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="counterClockwise" lowerBound="1"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="2"
        upperBound="-1" eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turnout" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="notConnectedSection" lowerBound="1"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="twoSectionsInClockwiseDirection"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rectangle" lowerBound="1"
        eType="#//Rectangle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turn" eSuperTypes="#//Section"/>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle">
    <eOperations name="isPointInside" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="point" eType="#//Point"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseMatrix" ordered="false"
        unique="false" upperBound="8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnglishTurnout" eSuperTypes="#//Turnout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="notConnectedClockwiseSection"
        lowerBound="1" eType="#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlindTrack" eSuperTypes="#//Section"/>
</ecore:EPackage>
