// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Enums.proto*\370\002\n\013MessageType\022\010\n\004NULL\020\000\022" +
      "\023\n\017SEGMENT_COMMAND\020\001\022\021\n\rSEGMENT_STATE\020\002\022" +
      "\031\n\025TRAIN_CURRENT_SEGMENT\020\003\022\027\n\023TRAIN_CURR" +
      "ENT_SPEED\020\004\022\033\n\027TRAIN_DIRECTION_COMMAND\020\005" +
      "\022\032\n\026TRAIN_FUNCTION_COMMAND\020\006\022\031\n\025TRAIN_RE" +
      "FERENCE_SPEED\020\007\022!\n\035TRAIN_REFERENCE_SPEED" +
      "_COMMAND\020\010\022\023\n\017TURNOUT_COMMAND\020\t\022\021\n\rTURNO" +
      "UT_STATE\020\n\022\025\n\021SEGMENT_OCCUPANCY\020\013\022\026\n\022YAK" +
      "INDU_RELEASE_TO\020\014\022\035\n\031YAKINDU_RESERVE_RES" +
      "ULT_TO\020\r\022\026\n\022YAKINDU_RESERVE_TO\020\016*.\n\021Segm",
      "entStateValue\022\014\n\010DISABLED\020\000\022\013\n\007ENABLED\020\001" +
      "*0\n\023TrainDirectionValue\022\013\n\007FORWARD\020\000\022\014\n\010" +
      "BACKWARD\020\001*0\n\021TurnoutStateValue\022\014\n\010STRAI" +
      "GHT\020\000\022\r\n\tDIVERGENT\020\001*/\n\025SegmentOccupancy" +
      "Value\022\010\n\004FREE\020\000\022\014\n\010OCCUPIED\020\001*=\n\032Yakindu" +
      "ConnectionDirection\022\010\n\004LEFT\020\000\022\t\n\005RIGHT\020\001" +
      "\022\n\n\006BOTTOM\020\002B0\n,hu.bme.mit.inf.modes3.me" +
      "ssaging.mms.messagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
