// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainCurrentSegment.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class TrainCurrentSegmentOuterClass {
  private TrainCurrentSegmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrainCurrentSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrainCurrentSegment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TrainCurrentSegment.proto\"9\n\023TrainCurr" +
      "entSegment\022\017\n\007trainID\030\001 \001(\r\022\021\n\tturnoutID" +
      "\030\002 \001(\rB0\n,hu.bme.mit.inf.modes3.messagin" +
      "g.mms.messagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TrainCurrentSegment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TrainCurrentSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrainCurrentSegment_descriptor,
        new java.lang.String[] { "TrainID", "TurnoutID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
