// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf enum {@code YakinduConnectionDirection}
 */
public enum YakinduConnectionDirection
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CW = 0;</code>
   */
  CW(0),
  /**
   * <code>CCW = 1;</code>
   */
  CCW(1),
  /**
   * <code>Y_TOP = 2;</code>
   */
  Y_TOP(2),
  /**
   * <code>Y_DIVERGENT = 3;</code>
   */
  Y_DIVERGENT(3),
  /**
   * <code>Y_STRAIGHT = 4;</code>
   */
  Y_STRAIGHT(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CW = 0;</code>
   */
  public static final int CW_VALUE = 0;
  /**
   * <code>CCW = 1;</code>
   */
  public static final int CCW_VALUE = 1;
  /**
   * <code>Y_TOP = 2;</code>
   */
  public static final int Y_TOP_VALUE = 2;
  /**
   * <code>Y_DIVERGENT = 3;</code>
   */
  public static final int Y_DIVERGENT_VALUE = 3;
  /**
   * <code>Y_STRAIGHT = 4;</code>
   */
  public static final int Y_STRAIGHT_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static YakinduConnectionDirection valueOf(int value) {
    return forNumber(value);
  }

  public static YakinduConnectionDirection forNumber(int value) {
    switch (value) {
      case 0: return CW;
      case 1: return CCW;
      case 2: return Y_TOP;
      case 3: return Y_DIVERGENT;
      case 4: return Y_STRAIGHT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<YakinduConnectionDirection>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      YakinduConnectionDirection> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<YakinduConnectionDirection>() {
          public YakinduConnectionDirection findValueByNumber(int number) {
            return YakinduConnectionDirection.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor()
        .getEnumTypes().get(5);
  }

  private static final YakinduConnectionDirection[] VALUES = values();

  public static YakinduConnectionDirection valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private YakinduConnectionDirection(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:YakinduConnectionDirection)
}

