---
- hosts: root
  remote_user: pi
  tasks:
  - include: utils/deploy-gradle.yaml service_name=dashboard
  - include: utils/deploy-gradle.yaml service_name=occupancyquery
  - include: utils/deploy-gradle.yaml service_name=touchboard
  - include: utils/deploy-systemd.yaml service_name=xpressnet