---
- name: Configure nrpe on masters
  hosts: modes3-bbb
  remote_user: debian
  sudo: yes

  tasks:
      - name: Install packages
        apt: name={{item}} state=present
        with_items:
              - nagios-plugins
              - nagios-nrpe-server

      - name: Create nrpe.cfg.old
        copy: remote_src=True src=/etc/nagios/nrpe.cfg dest=/etc/nagios/nrpe.cfg.old

      - name: Configure nrpe
        template:
          src="files/nrpe.cfg"
          dest="/etc/nagios/nrpe.cfg"
          mode=0644

      - name: Restart services
        service: name=nagios-nrpe-server state=restarted
