---
- name: Apply configuration on master BeagleBones
  hosts: modes3-bbb
  remote_user: debian
  gather_facts: no

  tasks:
      - name: restart machine
        shell: sleep 2 && shutdown -r now
        async: 1
        poll: 0
        sudo: yes
        ignore_errors: true
