---
- name: Deploy Oracle Java
  hosts: modes3-bbb
  remote_user: debian
  sudo: yes

  tasks:
      - name: Add Oracle repo1
        shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
        register: repostable1

      - name: Add Oracle repo2
        shell: echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
        when: repostable1|success
        register: repostable2

      - name: Add Oracle repo key
        apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886
        when: repostable2|success
        register: keystable

      - name: Accept Oracle license
        shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo /usr/bin/debconf-set-selections
        when: keystable|success
        register: license_accepted

      - name: Install Oracle java
        apt: name=oracle-java8-installer state=present update_cache=yes
        when: license_accepted|success
        register: java_installed

      - name: Set environmental variable
        apt: name=oracle-java8-set-default state=present
        when: java_installed|success
