---
- name: Create-swap
  hosts: modes3-bbb
  remote_user: debian
  sudo: yes

  tasks:
      - name: Create swap directory
        file: path=/var/cache/swap state=directory

      - name: Create swap file
        shell: dd if=/dev/zero of=/var/cache/swap/swapfile bs=1M count=256
        register: dd

      - name: Limit access to root
        file: path=/var/cache/swap/swapfile mode=0600

      - name: Create swap
        shell: mkswap /var/cache/swap/swapfile
        when: dd|changed
        register: mkswap

      - name: Enable swap
        shell: swapon /var/cache/swap/swapfile
        when: mkswap|changed

      - name: add entry to /etc/fstab          
        lineinfile: dest=/etc/fstab
                    line="/var/cache/swap/swapfile    none    swap    sw    0   0"
                    state=present                                                                                            

