<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="railroadmodel" nsURI="http://hu.bme.mit.inf.safetylogic.railroadmodel"
    nsPrefix="railroadmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyOn" lowerBound="1"
        eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previouslyOn" lowerBound="1"
        eType="#//RailRoadElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailRoadElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="2"
        upperBound="-1" eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connected" upperBound="-1"
        eType="#//RailRoadElement" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyConnected" upperBound="-1"
        eType="#//RailRoadElement" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viablePaths" upperBound="-1"
        eType="#//Path" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turnout" eSuperTypes="#//RailRoadElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rectangle" lowerBound="1"
        eType="#//Rectangle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="top" lowerBound="1" eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="straight" lowerBound="1"
        eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="divergent" lowerBound="1"
        eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentlyDivergent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailRoadModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//RailRoadElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseMatrix" ordered="false"
        unique="false" lowerBound="1" upperBound="8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="#//RailRoadElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedTo" lowerBound="1"
        upperBound="2" eType="#//RailRoadElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="via" eType="#//RailRoadElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//RailRoadElement"/>
  </eClassifiers>
</ecore:EPackage>
