#!/bin/sh
SERVICE_NAME="Master MQTT Controller"
PATH_TO_JAR="{{item.value.jar_dest}}"
PARAMETERS="{{item.value.jar_parameters}}"
PID_PATH_NAME="/var/run/{{item.key}}.pid"

export TURNOUT_ID=0x{{turnout_id}}

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java {{item.value.parameters}} -jar $PATH_TO_JAR $PARAMETERS 2> /var/log/{{item.key}}.error > /var/log/{{item.key}}.log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR $PARAMETERS 2> /var/log/{{item.key}}.error > /var/log/{{item.key}}.log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac

