// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentControl.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class SegmentControlOuterClass {
  private SegmentControlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SegmentControl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SegmentControl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SegmentControl.proto\"\200\001\n\016SegmentContro" +
      "l\022\021\n\tsegmentID\030\001 \001(\r\0222\n\014controlState\030\002 \001" +
      "(\0162\034.SegmentControl.ControlState\"\'\n\014Cont" +
      "rolState\022\013\n\007DISABLE\020\000\022\n\n\006ENABLE\020\001B0\n,hu." +
      "bme.mit.inf.modes3.messaging.mms.message" +
      "sP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SegmentControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SegmentControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SegmentControl_descriptor,
        new java.lang.String[] { "SegmentID", "ControlState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
