// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf enum {@code TrainDirectionValue}
 */
public enum TrainDirectionValue
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FORWARD = 0;</code>
   */
  FORWARD(0),
  /**
   * <code>BACKWARD = 1;</code>
   */
  BACKWARD(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FORWARD = 0;</code>
   */
  public static final int FORWARD_VALUE = 0;
  /**
   * <code>BACKWARD = 1;</code>
   */
  public static final int BACKWARD_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TrainDirectionValue valueOf(int value) {
    return forNumber(value);
  }

  public static TrainDirectionValue forNumber(int value) {
    switch (value) {
      case 0: return FORWARD;
      case 1: return BACKWARD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TrainDirectionValue>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TrainDirectionValue> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TrainDirectionValue>() {
          public TrainDirectionValue findValueByNumber(int number) {
            return TrainDirectionValue.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final TrainDirectionValue[] VALUES = values();

  public static TrainDirectionValue valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TrainDirectionValue(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TrainDirectionValue)
}

