// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TurnoutControl.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class TurnoutControlOuterClass {
  private TurnoutControlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TurnoutControl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TurnoutControl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024TurnoutControl.proto\"\204\001\n\016TurnoutContro" +
      "l\022\021\n\tturnoutID\030\001 \001(\r\0222\n\014controlState\030\002 \001" +
      "(\0162\034.TurnoutControl.ControlState\"+\n\014Cont" +
      "rolState\022\014\n\010STRAIGHT\020\000\022\r\n\tDIVERGENT\020\001B0\n" +
      ",hu.bme.mit.inf.modes3.messaging.mms.mes" +
      "sagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TurnoutControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TurnoutControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TurnoutControl_descriptor,
        new java.lang.String[] { "TurnoutID", "ControlState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
